#!/usr/bin/env sh

gui="flameshot gui"
screen="flameshot screen"
full="flameshot full"
flame="which flameshot"

if [ !"$flame" >> /dev/null ]; then
        sudo pkg install flameshot


fi 

echo "1. "$gui" "
echo "2. "$screen" "
echo "3. "$full" "

read -r choice

if [ "$choice" = 1 ]; then
         flameshot gui
         exit

elif [ "$choice" = 2 ]; then
         flameshot screen 
         exit


elif [ "$choice" = 3 ]; then
         flameshot full
         exit

else
      echo "Error: Wrong option Choose 1-3"
      exit

fi 
